config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'homes#top'

  #deviseのカスタムコントローラを使用
  devise_for :users, controllers: {
    session:       'users/sessions',
    registrations: 'users/registrations'
  }





  resources :users do
    member do
      delete :hide, as: 'users_hide'
    end
 end


  resources :homes,         only:[:top, :about]
  resources :scores,        only:[:index, :show, :create, :update, :destroy]
  resources :answers,       only:[:create, :update]
  resources :relationships, only:[:create, :destroy]


  resources :quizzes,     only:[:index, :show] do
    member do
      post :check_answer
    end
    collection do
      get  :finished
      post :start
    end
  end

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :authenticate_user!, only:[:index, :show, :check_answer, :finished]

  def index
    @genre = params[:genre]
    if @genre
      all_quiz_ids = Quiz.where(genre: @genre).pluck(:id)
      answered_quiz_ids = current_user.scores.where(quiz_id: all_quiz_ids).pluck(:genre_id)
      remember_quiz_ids = all_quiz_ids - answered_quiz_ids
      @remember_quizzes = remember_quiz_ids.size

      if remember_quiz_ids.empty?
        # すべての問題が終了したときの処理
        # （ここでは、スコアをリセットしてリダイレクトする例）
        current_user.scores.where(quiz_id: all_quiz_ids).destroy.all
        return
      end

      quiz_id = remember_quiz_ids.sample
    else
      quiz_id = Quiz.pluck(:id).sample
    end

    quiz_data = Quiz.random_question_by_id(quiz_id)
    @quiz = Quiz.find(quiz_data[:id])
    @question = quiz_data[:question]
    @answer = quiz_data[:answer]
    @total_score = 0
    @image_url = @quiz.image_url

     #JSONレスポンスを返す
     respond_to do |format|
       format.html
         format.json do
           render json: {
             id: @quiz.id,
             question: @question,
             total_score: @total_score,
             image_url: @image_url,
             remember_quizzes: @remember_quizzes
           }
         end
      end
  end



  # def index
  #   if params[:genre]
  #     quiz_data = Quiz.random_question(params[:genre])
  #   else
  #     quiz_data = Quiz.random_question
  #   end
  #   @quiz = Quiz.find(quiz_data[:id])
  #   @question = quiz_data[:question]
  #   @answer = quiz_data[:answer]
  #   @total_score = 0
  #   @image_url = @quiz.image_url
  # end

  def show
  end

  def check_answer
    @quiz = Quiz.find(params[:id]) #問題のIDを取得
    answer = answer_params

    if @quiz.content.downcase == params[:answer].downcase
       #ユーザー出した答え(params[:answer])とDBに保存されている正解(@questions.answer)を比較している
       score = current_user.scores.create(point: 10, quiz_id: @quiz.id)
       @next_quiz = Quiz.where("id > ?", @quiz.id).first #正解したら次の問題(@question.id)に1を加える
       total_score = current_user.scores.sum(:point)

       if @next_quiz
         all_quiz_ids = Quiz.where(genre: @quiz.genre).pluck(:id)
         answered_quiz_ids = current_user.scores.where(quiz_id: all_quiz_ids).pluck(:quiz_id)
         remember_quiz_ids = all_quiz_ids - answered_quiz_ids

         question = hide_random_char(@next_quiz.content)
         render json: {
           status: 'success',
           question: question,
           id: @next_quiz.id,
           total_score: total_score,
           image_url: @next_quiz.image_url, #画像URL追加
           remember_quizzes: remember_quiz_ids.size, #この理問題数を追加
           meaning: @quiz.meaning #英単語クイズの意味
           }
       else
         render json: {
           status: 'finished',
           user_path: user_path(current_user)
           }
       end
    else
      score = current_user.scores.create(point: -10, quiz_id: @quiz.id)
      @next_quiz = Quiz.where("id > ?", @quiz.id).first
      total_score = current_user.scores.sum(:point)
      render json: { status: 'error', message: '不正解です。もう1度挑戦しよう!!',
      total_score: total_score,
      meaning: @quiz.meaning
      }
    end
  end

  def start
    current_user.scores.destroy_all
    redirect_to quizzes_path
  end

  def finished
  end

  private

  def hide_random_char(content) #引数contentは置き換える文字列のこと
    replace_count = (content.length.to_f / 2).ceil #contentのlength(長さ)を取得しそれを浮動小数点(to_f)に変換
    #ceilメソッドは小数点切り上げ。この結果文字列の長さの半分以上がreplace_countに代入される
    replace_count.times do
      random_index = rand(content.length) #0からcontentの長さまでのランダムな整数を生成
      while content[random_index] == '_' #ループ開始
        random_index = rand(content.length) #ランダムなインデックスを生成し代入
      end
      content[random_index] = '_' #random_indexの位置にある文字を"_"に置き換え
    end
    content #置き換えが行われた結果の文字列か返される
  end

  def answer_params
    params.require(:answer)
  end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/finished.html.erb
<%= render 'layputs_header' %>

<h1>おめでとうございます！</h1>
<span>全ての問題を解答しました！</span>

app/views/quizzes/index.html.erb
<%= render 'layouts/header' %>
<% Quiz.pluck(:genre).uniq.each do |genre| %>
  <%= link_to genre, quizzes_path(genre: genre), class: 'quiz-genre' %>
<% end %>

<div class="d-flex justify-content-center align-items-center" style="height: 90vh;">
  <div id="quiz-div" style="display: none;">
    意味: <div id="meaning"></div>
    <div id="total-score"><%= @total_score %></div> Point
    <h2 id="how-many-quizzes">残り問題数: <%= @remember_quizzes %></h2>
    <h1><%= params[:genre] ? params[:genre]: '英単語クイズ' %></h1>
    <span id="question"><%= @question %></span>
    <%= form_with(url: check_answer_quiz_path(@quiz), method: "post", id: "quiz-form", local: false, data: { turbo: false }) do %>
      <%= text_field_tag :answer,  '', id: 'answer' %>
      <%= hidden_field_tag :correct_answer, @answer %>
      <%= submit_tag "解答" %>
    <% end %>
    <%= button_to 'リセット', start_quizzes_path, method: :post %>
      <img id="quiz-image" src="<%= @quiz.image_url %>" alt="<%= @quiz.content %> image" style="width: 300px; height: 300px; border-radius: 20px;">
      <%#= link_to '次の問題へ', quizzes_path(genre: params[:genre]), method: :get, class: 'btn btn-primary' %>
  </div>
</div>
<%= javascript_include_tag 'quiz_index' %>