config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'homes#top'

  #deviseのカスタムコントローラを使用
  devise_for :users, controllers: {
    session:       'users/sessions',
    registrations: 'users/registrations'
  }





  resources :users do
    member do
      delete :hide, as: 'users_hide'
    end
 end


  resources :homes,         only:[:top, :about]
  resources :scores,        only:[:index, :show, :create, :update, :destroy]
  resources :answers,       only:[:create, :update]
  resources :relationships, only:[:create, :destroy]


  resources :quizzes,     only:[:index, :show] do
    member do
      post :check_answer
    end
    collection do
      get  :finished
      post :start
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  validates :username,  presence: true
  validates :email, presence: true

  has_many :scores

  has_one_attached :profile_image

  def total_score
    scores.sum(:point)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :profile_image)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :profile_image)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only:[:index, :show, :edit, :update, :destroy]
  before_action :check_user_status,  only:[:show]

  def index
    @all_users = User.all
    @users = User.where(is_deleted: false) #退会済みではないユーザーのみ一覧に表示
  end

  def hide
    @user = User.find(params[:id])
    @user.update(is_deleted: true) #trueは退会してるかのことtrue=退会ずみ, false=退会済みでない
    reset_session
    flash[:notice] = "またのご利用心よりお待ちしております。"
    redirect_to root_url
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(update_params)
      flash[:notice] = "編集に成功しました。再度ログインしてください"
      redirect_to (@user)
    else
      p @user.errors
      render 'edit'
    end
  end

  private

  def check_user_status
    user = User.find(params[:id])
    if user.is_deleted
      flash[:noitce] = "ユーザーは退会済みです"
      redirect_to root_url
    end
  end

  def update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end


   def user_params
    params.require(:user).permit(:email, :username, :profile_image, :password, :password_confirmation)
   end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render 'layouts/header' %>

<div class="signup-body">
  <div class="signup-page">
    <div class="form">
      <div class="mb-4">Edit Your Account??</div>
      <%= form_with(model: @user, local: true) do |f| %>
        <%= render "devise/shared/error_messages", resource: @user %>
        <%= f.text_field :username, autofocus: true, autocomplete: "UserName", class: "form-control", placeholder: "username" %>
        <%= f.email_field :email, autofocus: true, autocomplete: "Email", class: "form-control", placeholder: "email" %>
        <%= f.password_field :password, autofocus: true, autocomplete: "password", class: "form-control", placeholder: "Password" %>
        <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control", placeholder: "Password_Confirmation" %>

        <%= f.submit "Edit Your Profile!!", class: "form-submit" %>
        <p class="message">Back <%= link_to "Go To Top Page", root_url %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'layouts/header' %>

<% @users.each do |user| %>
  <p><%= user.username %></p>
  <p><%= user.email %></p>
  <p>Point: <%= user.total_score %></p>
<% end %>

app/views/users/show.html.erb
<%= render 'layouts/header' %>

<h1>合計獲得ポイント</h1>

<span>total score: <%= @user.total_score%></span>Point

<p>ユーザーネーム: <%= @user.username %></p>

<p>メールアドレス: <%= @user.email %></p>

<p>最終ログイン: <%= @user.current_sign_in_at.strftime("%Y年%m月%d日") %></p>

<%= link_to "ユーザー編集", edit_user_path %>

<% if user_signed_in? && @user.id == current_user.id %>
  <%= link_to "退会", users_hide_user_path(current_user), data: { turbo_method: :delete, turbo_confirm: '本当に退会しますか？' } %>
<% end %>

<h1>仮</h1>