config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'homes#top'

  #deviseのカスタムコントローラを使用
  devise_for :users, controllers: {
    session:       'users/sessions',
    registrations: 'users/registrations'
  }





  resources :users do
    member do
      delete :hide, as: 'users_hide'
    end
 end


  resources :homes,         only:[:top, :about]
  resources :scores,        only:[:index, :show, :create, :update, :destroy]
  resources :answers,       only:[:create, :update]
  resources :relationships, only:[:create, :destroy]


  resources :quizzes,     only:[:index, :show] do
    member do
      post :check_answer
    end
    collection do
      get  :finished
      post :start
    end
  end

end

app/views/layouts/_footer.html.erb
<footer id="footer" class="border-top bg-white fixed"style="height:50px;margin-top:600px;">
  <ul>
  <li class="list-inline-item"><img src="https://qumeru-media-preview.s3-ap-northeast-1.amazonaws.com/preview/Bootstrap/237/preview3/%E3%82%A4%E3%83%A9%E3%82%B9%E3%83%88111.png"style="height:50px"></li>
  <li class="list-inline-item"><a href="#">お問い合わせ</a></li>
  <li class="list-inline-item"><a href="#">採用情報</a></li>
  <li class="list-inline-item"><a href="#">運営会社</a></li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<body>
  <!-- ナビゲーションバー -->
  <nav class="navbar navbar-light bg-light fixed">
    <!-- タイトル -->
    <%= link_to "EnglishDoJo", root_url %>
    <!-- ハンバーガーメニュー -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- ナビゲーションメニュー -->
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to "Home", root_url %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "マイページ", user_path(current_user) %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "新規会員登録", new_user_registration_path %>
        </li>
        <li class="nav-item">
          <%= link_to "全てのユーザー", users_path %>
        </li>
        <li class="nav-item">
          <%= link_to "ログイン", new_user_session_path %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </li>
        <li class="nav-item">
          <%= link_to "クイズへゴー", quizzes_path %>
        </li>
      </ul>
    </div>
  </nav>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EnglishDoJo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible fade show position-fixed fixed-top w-25 ml-auto mt-3 mr-3" role="alert">
    <%= value %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

  <body>
    <%= yield %>
  </body>
</html>